// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgyzlpnvhklyrthuigwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJneXpscG52aGtseXJ0aHVpZ3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NTIzMTcsImV4cCI6MjA1NTUyODMxN30.7P70hDwe-v7HX7j_gnGDcPyDSHm8xWsjHg-K3ENuA3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);